namespace NiceHashMinerLegacy.Common.Enums
{
    public enum AlgorithmType
    {
        ZIL = -120,

        // dual algos for grouping
        AutolykosZil = -73,
        FishHashPyrinHash = -39,
        OctopusPyrinHash = -38,
        AutolykosPyrinHash = -37,
        FishHashAlephium = -36,
        FishHashKarlsenHash = -35,
        OctopusAlephium = -34,
        AutolykosAlephium = -33,
        DaggerAlephium = -32,
        ETCHashAlephium = -31,
        OctopusKarlsenHash = -30,
        AutolykosKarlsenHash = -29,
        DaggerKarlsenHash = -28,
        ETCHashKarlsenHash = -27,
        KAWPOWLite = -26,
        OctopusIronFish = -25,
        AutolykosIronFish = -24,
        DaggerIronFish = -23,
        ETCHashIronFish = -22,
        OctopusKHeavyHash = -21,
        AutolykosKHeavyHash = -20,
        DaggerKHeavyHash = -19,
        ETCHashKHeavyHash = -18,
        DaggerOctopus = -17,
        DaggerKAWPOW = -16,
        DaggerAutolykos = -15,
        DaggerHashimoto4GB = -12,
        DaggerHandshake = -11,
        DaggerEaglesong = -10,
        DaggerHashimoto3GB = -9,
        DaggerKeccak = -8,
        DaggerBlake2s = -7,
        DaggerSia = -6,
        DaggerDecred = -5,
        DaggerLbry = -4,
        DaggerPascal = -3,
        INVALID = -2,
        NONE = -1,
        #region NiceHashAPI

        Keccak_UNUSED = 5,
        Nist5_UNUSED = 7,

        Empty = 0,
        SHA256_UNUSED = 1,
        ScryptNf_UNUSED = 2,
        X11_UNUSED = 3,
        X13_UNUSED = 4,
        //Keccak_UNUSED = 5,
        X15_UNUSED = 6,
        //Nist5_UNUSED = 7,

        WhirlpoolX_UNUSED = 10,
        Qubit_UNUSED = 11,
        Quark_UNUSED = 12,
        Axiom_UNUSED = 13,

        ScryptJaneNf16_UNUSED = 15,
        Blake256r8_UNUSED = 16,
        Blake256r14_UNUSED = 17,
        Blake256r8vnl_UNUSED = 18,
        // UNUSED END

        NeoScrypt = 8,
        Lyra2RE_UNUSED = 9,

        Lyra2REv2_UNUSED = 14,

        Hodl_UNUSED = 19,
        DaggerHashimoto = 20,
        Decred_UNUSED = 21,
        CryptoNight_UNUSED = 22,
        Lbry_UNUSED = 23,
        Equihash_UNUSED = 24,
        Pascal_UNUSED = 25,
        X11Gost_UNUSED = 26,
        Sia_UNUSED = 27,
        Blake2s_UNUSED = 28,
        Skunk_UNUSED = 29,
        CryptoNightV7_UNUSED = 30,

        CryptoNightHeavy_UNUSED = 31,
        Lyra2z_UNUSED = 32,
        X16R_UNUSED = 33,
        CryptoNightV8_UNUSED = 34,
        sha256asicboost_UNUSED = 35,
        ZHash = 36,
        Beam_UNUSED = 37,
        GrinCuckaroo29_UNUSED = 38,
        GrinCuckatoo31_UNUSED = 39,
        Lyra2REv3_UNUSED = 40,
        MTP_UNUSED = 41,
        CryptoNightR_UNUSED = 42,
        CuckooCycle = 43,
        GrinCuckarood29_UNUSED = 44,
        BeamV2_UNUSED = 45,
        X16RV2 = 46,
        RandomX = 47,
        Eaglesong_UNUSED = 48,
        Cuckaroom_UNUSED = 49,
        GrinCuckatoo32 = 50,
        Handshake_UNUSED = 51,
        KAWPOW = 52,
        Cuckaroo29BFC_UNUSED = 53,
        BeamV3 = 54,
        CuckaRooz29_UNUSED = 55,
        Octopus = 56,
        Autolykos = 57,
        ZelHash = 58,
        Kadena_UNUSED = 59,
        ETCHash = 60,
        VerusHash = 61,
        KHeavyHash__UNUSED = 62,
        NexaPow = 63,
        IronFish_UNUSED = 64,
        KarlsenHash = 65,
        Alephium = 66,
        FishHash = 67,
        PyrinHash = 68
        #endregion // NiceHashAPI
    }
}
